### ISSUE TITLE
org-store-link exists with error, denote-retrieve-filename-identifier should not error

### ISSUE THREAD

**Issue by benjamin-asdf** [protesilaos/denote#107]
To reproduce I call `org-store-link` in a non denote file buffer.

Denote adds `denote-retrieve-filename-identifier` as org link store func. This get's called with impunity by `org-store-link`, so it errors out.   Either the `store` func does not throw an error, or `org-store-link` should treat errors as `nil`.

**Comment by protesilaos** [comment]
Hello @benjamin-asdf!

Are you using the latest commit in the git repo?  Just t be sure we are working with the same code.

> Denote adds `denote-retrieve-filename-identifier` as org link store func. This get's called with impunity by `org-store-link`, so it errors out.   Either the `store` func does not throw an error, or `org-store-link` should treat errors as `nil`. 

Maybe I am not reproducing it correctly.  On my end, `org-store-link` in a non-Denote file uses the `file:` link type.

Looking at the `denote-link-ol-store`, the condition is to check for `denote-file-is-note-p` before proceeding.  If that returns nil, it aborts.

I tried the following code in a non-Denote Org buffer.  Type `M-:`, insert the code and hit RET to evaluate it.  It should return nil instead of showing `We are here`.

```elisp
(when-let* ((file (buffer-file-name))
            ((denote-file-is-note-p file))
            (file-type (denote-filetype-heuristics file))
            (file-id (denote-retrieve-filename-identifier file))
            (file-title (denote--retrieve-title-or-filename file file-type)))
  (message "We are here"))
```

**Comment by benjamin-asdf** [comment]
@protesilaos yea I have the issue on `6374751ee20be95637dcf5eefd52c0da321158a6`

**Comment by protesilaos** [comment]
@benjamin-asdf Do you get a backtrace with the error?  Can you please post it here?  It will help me trace the problem.

**Comment by benjamin-asdf** [comment]
updated previous comment. It is fixed on 
9b969da55c84e52ce3be4dd163e7d1f081209dab

**Comment by protesilaos** [comment]
Very well!  I am closing this issue then.  Thanks for your time!
