### ISSUE TITLE
Excluding dot directories from denote-file-prompt

### ISSUE THREAD

**Issue by mgmarlow** [protesilaos/denote#111]
Certain temporary artifacts show up in my `denote-file-prompt` buffer after enabling Google Drive (`.tmp` in this example, though there may be one or two extras in a real setup):

![Screen Shot 2022-11-04 at 8 27 39 AM](https://user-images.githubusercontent.com/3778552/200014378-b80a84c7-e7d4-41c6-807d-4ca2058f69bc.png)

I'd like to filter these sorts of files out from my `denote-file-prompt` minibuffer, in my case all dotfile directories. I'm rather new to Emacs, so I'm not sure whether there's an easy alternative that I'm missing that wouldn't require a modification to the package.

I have some changes ready to put up in PR, but I wanted to run this feature by you and see whether you think such a thing would benefit the package. Thanks!

**Comment by protesilaos** [comment]
Hello @mgmarlow!

Yes, this is a useful addition.  Since you have the changes, please go ahead with the PR.  Or, generally, do whatever is easier for you.

This issues was brought up before, but we never found an optimal solution.  I would prefer such a feature to be optional and opt-in by default.  What do you think?

**Comment by mgmarlow** [comment]
Agreed, I was thinking along the same lines. Since denote is opinionated about filenames but not directories, this is more of a convenience feature than anything else. I'll get that PR posted!

**Comment by protesilaos** [comment]
Thank you!
