### ISSUE TITLE
conceptual similarities to date2name and filetags

### ISSUE THREAD

**Issue by nbehrnd** [protesilaos/denote#117]
Because of GitHub's panel «packages which might be of interest for you», I just discover your approach.

Conceptually, the provision of a consistent time stamp and assigning a keyword from a constrained vocabulary bears similarities to Karl Voit's earlier implementations in Python [date2name](https://github.com/novoid/date2name) and [filetags](https://github.com/novoid/filetags) as applications for the CLI.  So, perhaps his talk [*Grazer Linuxtage 2018 - The Advantages of File Name Conventions and Tagging*](https://www.youtube.com/watch?v=rckSVmYCH90) (link to a 45min video recording on youtube) equally is of interest for you/users of your approach for Emacs.

**Comment by novoid** [comment]
Coming from Org-mode and its Zettelkasten implementations, I did not realize the similarities between denote and filetags/date2name myself. ;-)

But yes, there are similarities in the concept.

@protesilaos, how would you value the use of denote for file management without knowledge-management/Zettelkasten/...?

**Comment by protesilaos** [comment]
Hello @nbehrnd and thanks for sharing this information!  I cannot watch the video right now.  Will do it over the weekend.

I follow @novoid blog and have read many articles therein, though I have not used those packages you mention.  The reason is that I learnt about them after I already had my own workflow in place.

As Karl notes, the concept is the same: give file names a predictable file name and be consistent about it.  Once those are granted, I don't think there is an inherently better way of doing things.  It comes down to what the user prioritises.  For example, Karl's dates are more readable and thus easy to parse with the eye, though they use hyphens which means that it is more difficult to anchor a search at a certain section of the file name.  By contrast, Denote's dates (the identifier) are more terse but free up the hyphen to be used as a delimiter.  To quote from the manual:

> File names have three fields and two sets of field delimiters between them:
> 
>     DATE--TITLE__KEYWORDS.EXTENSION
> 
> [...] Consider this example:
> 
>     20220621T062327--introduction-to-denote__denote_emacs.txt
> 
> You will notice that there are two matches for the word `denote`: one in the title field and another in the keywords' field.  Because of the distinct field delimiters, if we search for `-denote` we only match the first instance while `_denote` targets the second one.  When sorting through your notes, this kind of specificity is invaluable---and you get it for free from the file names alone!
>
> <https://protesilaos.com/emacs/denote#h:1a953736-86c2-420b-b566-fb22c97df197>

* * *

>  how would you value the use of denote for file management without knowledge-management/Zettelkasten/...?

In terms of file names, I make no distinction between those concepts.  They all have the same file-naming scheme (Denote has commands to name and rename existing files).  Differences are found in the filesystem, such as different directories, and then the file extension.  PDFs and such are longer-term storage, whereas Org, Markdown, and plain text are "notes".

Concretely, my videos are in `~/Videos`, my notes in `~/Documents/notes`, and my books in `~/Documenrs/books` (among others).

Overall, this works for me as Denote's file names are not specific to a certain type of file or purpose.

**Comment by novoid** [comment]
On https://github.com/novoid/filetags you can find my file name convention summary:

`(<ISO date/time stamp>)?(?<descriptive file name>)?( -- <list of tags separated by spaces>)?.<file extension>`

In Prot's simplified notation from above:

`DATE TITLE -- TAG1 TAG2.EXTENSION`

As a user, I prefer my file name convention because I tend to read them very frequently in my daily work as I work in the shell. As Prod mentioned, my convention is easier to parse by humans. I got the impression that Prot is using his files mostly as links in his Org mode as references, not necessarily reading their file name that often (please correct me if I did get this wrong).

For the interested user, it is clearly visible that I let go of the "never use spaces or special characters in file- and directory names" many years ago (after strictly following this idea for many, many years). To me, all negative aspects of using special characters and spaces are gone due to almost perfect (zsh) support for tab completion, escaping and so forth. YMMV.

Using my `lfile` custom link method described on https://karl-voit.at/2022/02/10/lfile/ I may link to any file in my Org mode. I don't have to care about its path any more. I do have custom Elisp functions to integrate with dired and Org mode in [my config](https://github.com/novoid/dot-emacs/blob/master/config.org).

[With a similar method using Memacs](https://github.com/novoid/Memacs/blob/master/docs/memacs_filenametimestamps.org), I may also [embed arbitrary image files for lazyblorg blog articles](https://github.com/novoid/lazyblorg/wiki/Images#embedding-tsfile-image-files).

**Comment by protesilaos** [comment]
Thank you @nbehrnd!  In the Denote manual, I have a section titled "Alternative ideas with Emacs and further reading": <https://protesilaos.com/emacs/denote#h:188c0986-f2fa-444f-b493-5429356e75cf>.  Do you want to prepare a change there to mention Karl's tools?  I think a section right below makes sense, so that it does not mention "Emacs" in its heading.

If you don't know how to write in Org, please prepare the text in any format you prefer and I will do the conversion.
