### ISSUE TITLE
Denote Backlinks don't work when using silos

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/denote#129]
Hej @protesilaos,

thank you so much for denote, which I love to use on the regular. I have about 6 different silos each covering vastly different topics. They have a .dir-locals.el file with the following contents (so that keywords are not shared):
```
;;; Directory Local Variables.  For more information evaluate:
;;;
;;;     (info "(emacs) Directory Variables")

((nil . ((denote-directory . default-directory))))
```

It is just recently that I started exploiting the full capabilities of denote when adding a lot more links to any one note. This led me to notice a behaviour I don't quite understand: when calling the `denote-link-backlinks` function, I am inserted into a buffer showing the backlinks. However, when I try to open them by `RET`'ing on one of the backlinks, an empty file is opened. Wondering why that might be the case, I checked the file's path, only to realise that it is the path of `denote-directory` and not that of the silo containing the note whose backlinks I had displayed.

Is this by design, or is there a variable I can tweak to make this feature work as "exptected"?

This is my configuration:
```
(use-package denote
  :config
  (setq denote-directory "~/notes/denote/")
  (setq denote-known-keywords nil)
  (setq denote-sort-keywords nil)
  (setq denote-dired-directories (cdr (ffap-all-subdirs denote-directory)))
  :bind
  (("s-n n" . denote)
   ("s-n R" . denote-rename-file-using-front-matter)
   ("s-n r" . denote-rename-file)
   ("s-n c" . denote-link-or-create)
   ("s-n s" . denote-subdirectory)
   ("s-n k" . denote-keywords-add)))
```

Thanks a bunch, have a good time :)

**Comment by MirkoHernandez** [comment]
I have had some issues with `denote-directory`. My usual solution is to create a variation of that function so that it uses a  `my-base-denote-directory`. 

Here is a function that I use for navigation purposes  (usually I don't use the backlinks for reference).

```
(setq denote-link-backlinks-display-buffer-action 'split-window-right)

(defun my/denote-goto-backlink (&optional arg)
  (interactive)
  (let* ((default-directory   my-denote-base-directory)
	 (file (buffer-file-name))
	 (id (denote--retrieve-filename-identifier file)))
    (if-let ((files (delete file
			    (denote--retrieve-files-in-xrefs id))))
	(if (or arg (eq 1 (length files)))
	    (find-file (car files))
	  (find-file (completing-read  "" files)))
      (user-error "No links to the current note"))))
```
There is a package that can display the denote backlinks in a read only segment of the buffer. This approach seems to me the best for reference purposes.

**Comment by protesilaos** [comment]
Hello @hapst3r!

I have not had the chance to test this.  I will do it during the weekend and report back to you.

In general: the more testing we do on silos, the better we will understand what needs to be done to make them work at all times.

@MirkoHernandez 

> There is a package that can display the denote backlinks in a read only segment of the buffer. This approach seems to me the best for reference purposes.

Notwithstanding the need to fix this in denote.el, which package are you referring to?  We can document it in the manual so that users can find it as well.

**Comment by MirkoHernandez** [comment]
Sorry I could not remember the name (I tested this packages  a few weeks ago),  it is called denote-refs .  `https://github.com/emacsmirror/denote-refs`.

@protesilaos  with your help (previously provided code)  I have zero issues with the silos and links, but new  users could  find themselves experiencing problems with `denote-directory` and some denote functions when used inside a silo.

**Comment by protesilaos** [comment]
Hello again @hapst3r!  Time flies and I was not able to do this earlier.  I just pushed a change that may fix your problem.

```
commit 828af230607d7f0f2828175e4933d1fd017dc3cb
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Sun Feb 12 09:22:29 2023 +0200

    Make sure backlinks get correct 'denote-directory' path
    
    The backlinks buffer will now get the correct path when it is
    generated inside a silo.  This is related to issue 129 reported by
    hapst3r on the GitHub mirror:
    <https://github.com/protesilaos/denote/issues/129>.
    
    This change is necessary because .dir-locals do not work for buffers,
    so we must get the value from the file that calls 'denote-link-backlinks'.

 denote.el | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

```

**Comment by protesilaos** [comment]
I think we need to refine how we determine if a directory is or belongs to a silo.  I could not find a backward recursive way to do this, so I wrote something myself.

@MirkoHernandez Do you have any thoughts on this?

```diff
 denote.el | 52 +++++++++++++++++++++++++++++++++++++++++++++++-----
 1 file changed, 47 insertions(+), 5 deletions(-)

diff --git a/denote.el b/denote.el
index 1b437b7..3753f8e 100644
--- a/denote.el
+++ b/denote.el
@@ -136,6 +136,18 @@ (defcustom denote-directory (expand-file-name "notes" (xdg-user-dir "DOCUMENTS")
   :link '(info-link "(denote) Maintain separate directories for notes")
   :type 'directory)
 
+(defcustom denote-silo-nesting-depth 3
+  "How many levels up to check if current file is in a silo.
+Silos have a directory-local variable that isolates them from the
+default value of the variable `denote-directory'.  When the silo
+is a flat directory, Denote can easily know about it.  Otherwise
+it needs to search the parents of the current directory in order
+to determine if the current file belongs to a silo."
+  :group 'denote
+  :type 'natnum
+  :package-version '(denote . "1.3.0")
+  :link '(info-link "(denote) Maintain separate directories for notes"))
+
 (defcustom denote-known-keywords
   '("emacs" "philosophy" "politics" "economics")
   "List of strings with predefined keywords for `denote'.
@@ -477,13 +489,43 @@ (defun denote--completion-table (category candidates)
         `(metadata (category . ,category))
       (complete-with-action action candidates string pred))))
 
+(defun denote--silo-p (path)
+  "Return non-nil if PATH is a silo.
+Check if there exists a directory local value for the variable
+`denote-directory'."
+  (if (file-directory-p path)
+      (with-temp-buffer
+        (when-let* ((files (directory-files path))
+                    ((member ".dir-locals.el" files)))
+          (buffer-local-value
+           'denote-directory
+           ;; TODO 2023-02-12: Clean up the created buffer
+           (get-buffer-create (find-file-noselect path)))))
+    (error "PATH must be a directory")))
+
+(defun denote--get-silo-path (&optional file levels)
+  "Try to determine if FILE belongs to a silo.
+
+Operate recursively up to optional LEVELS.  If LEVELS is nil, use
+`denote-silo-nesting-depth'.
+
+If no silo is found, return nil.  See the function
+`denote-directory'."
+  (when-let* ((file (if (and file (file-exists-p file)) file default-directory))
+              (path (file-name-parent-directory file)))
+    (catch 'value
+      (dotimes (_n (or levels denote-silo-nesting-depth))
+        (if (denote--silo-p path)
+            (throw 'value path)
+          (setq path (file-name-parent-directory path))))
+      path)))
+
 (defun denote-directory ()
   "Return path of variable `denote-directory' as a proper directory."
-  (let* ((val (or (buffer-local-value 'denote-directory (current-buffer))
-                  denote-directory))
-         (path (if (or (eq val 'default-directory) (eq val 'local)) default-directory val)))
-    (unless (file-directory-p path)
-      (make-directory path t))
+  (let ((path (or (denote--get-silo-path)
+                  (unless (file-directory-p denote-directory)
+                    (make-directory denote-directory t))
+                  denote-directory)))
     (file-name-as-directory (expand-file-name path))))
 
 (defun denote--slug-no-punct (str)
```

I can share the code directly if it is easier that way.

**Comment by MirkoHernandez** [comment]
@protesilaos  I think that when using the `dir-local-variables-alist` variable it would be possible to differentiate when a specific silo is being used without the need for a recursive search. I still think that probably a denote-root-directory (or some similar functionality) is necessary for backlinks that reference a different silo. I'm still using a  `my/denote-goto-backlink` function for this reason.

Here is the reference code. Hopefully this is relevant, I'm confused as to what would be the desired changes, or added features.
```
(defun get-the-current-buffer-silo ()
  (alist-get 'denote-directory dir-local-variables-alist))

(setq silo (get-the-current-buffer-silo))

(cl-case silo
  ('default-directory (message "using the current dir as denote-directory"))
  ('nil (message "using default denote-directory" ))
  (t (message "path of the current silo" )))
```

**Comment by protesilaos** [comment]
@MirkoHernandez 

[ The diff I posted earlier is outdated.  I pushed a draft.  I followed it quickly with commit `9d048ba`. ]

The reason I added recursion is because silos can have subdirectories.  Consider this structure:

```
silo-root
|
|
---1-subdir
   |
   |
   ---1.1-subdir
```

In `silo-root` we have the `.dir-locals.el`: it sets `denote-directory` to `default-directory`.

When we are in either `1-subdir` or `1.1-subdir` and do `M-:` (`M-x eval-expression`) to evaluate the following snippet, we get `default-directory`.

```elisp
(alist-get 'denote-directory dir-local-variables-alist)
```

This means that we are treating the subdir as its own root directory, which is not what the user wants.

The recursion is meant to address this issue.  I am still looking at the code for possible optimisations, though I think what I have now proves the concept.

**Comment by nobiot** [comment]
@protesilaos @MirkoHernandez 

I will be risking confusing the discussion, but I would like to ask a question to clarify one thing, which is related to this.

> [ The diff I posted earlier is outdated. I pushed a draft. I followed it quickly with commit `9d048ba`. ]
> 
> The reason I added recursion is because silos can have subdirectories. Consider this structure:
> 
> ```
> silo-root
> |
> |
> ---1-subdir
>    |
>    |
>    ---1.1-subdir
> ```
> 
> In `silo-root` we have the `.dir-locals.el`: it sets `denote-directory` to `default-directory`.
> 
> When we are in either `1-subdir` or `1.1-subdir` and do `M-:` (`M-x eval-expression`) to evaluate the following snippet, we get `default-directory`.
> 
> ```emacs-lisp
> (alist-get 'denote-directory dir-local-variables-alist)
> ```
> 
> This means that we are treating the subdir as its own root directory, which is not what the user wants.

Using this example, I seem to be able to use subdirectories as intended if I just directly specify `silo-root` in `.dir-locals.el` instead of using `default-directory`.

```
;; Content of /home/nobiot/Documents/denote-test-local-dir/.dir-locals.el
((nil . ((denote-directory . "/path/to/silo-root"))))
```

Some recent commits (9d048ba449f5cade28efb4a3e37d25bf506cc6bc and fa8c3e6600318abe86b4a6e18b4c95dc9dfba633) seem to try hard to make subdirectories of silos work properly. Has this simply change in `.dir-locals.el` been considered?

I made [a comment in a previous related issue](https://github.com/protesilaos/denote/issues/114#issuecomment-1332443547) rather long ago and I haven't been able to keep up with the discussions on silos since, so I may be mixing things up and confuse the current discussion. If that is the case, I apologise. But if I go back to an old commit (4c8c8d1552a87e02446938f4f842e2600d256709), I see that backlinks among directories and subdirectories within a silo just work on my end. 

Could someone help me understand the current issue? I have implemented some of the changes in logic for backlinks, so I might be able to offer some help.

Thank you...

**Comment by protesilaos** [comment]
Hello @nobiot!  Note that the current implementation is not optimised anyway.  I wanted to put it out there to see if it has any obvious problems beside the known performance pentalty (which is super important).

My original intent with `default-directory` was what you have there as an explicit path.  I used to think it worked, but these bug reports keep appearing...  Can we have the `default-directory` evaluate to a path inside the `.dir-locals.el`?  I have not found documentation about it.

But yes, I agree that what I did is not a good approach and should be removed if a better alternative exists.

**Comment by nobiot** [comment]
@protesilaos 

>  Can we have the default-directory evaluate to a path inside the .dir-locals.el? 

What I have observed is that `default-directory` **does not work as users intend** when you have subdirectories inside the silo. As you noted, each subdirectory will be a silo on its own if you use `default-directory`. 

What users would usually want is that files in a silo with its all subdirectories to have `silo-root` as `denote-directory`. To achieve this, you would need to avoid `default-directory` and set `denote-directory` specifically to `silo-root` (and in fact, that's what you do in your init as well).

This is because `.dir-locals.el` gets evaluate for each file (as far as I could see with `edebug`); that is, using your example above with `silo-root / 1-subdir / 1.1-subdir`, `default-directory` resolves to the directory the file in question is stored: the files in `silo-root` will have `denote-directory` to be set to `silo-root`, the files in `1-subdir` will have `denote-directory` to be set to `1-subdir`, and so on.

I believe @MirkoHernandez or someone has also made the same observation and suggested to update the user manual -- I cannot locate it in GitHub mirror now, so I may be mistaken, but this would be worth considering.

I suggest you confirm the behavior I describe here. If it is indeed the behavior of `.dir-locals.el`, you might be able to revert some of the recent commits around backlinks for silos, avoid the performance issues, and resolve others that are now piling in...

**Comment by protesilaos** [comment]
@nobiot It is mentioned in the manual and I had forgotten about it: https://protesilaos.com/emacs/denote#h:15719799-a5ff-4e9a-9f10-4ca03ef8f6c5

> IMPORTANT If your silo contains sub-directories of notes, you should replace `default-directory` in the above examples with an absolute path to your silo directory, otherwise links from files within the sub-directories cannot be made to files in the parent directory. For example: [...]

What I meant earlier is that this is exactly what I intended `default-directory` to be: the symbol would be evaluated and its value would be stored as an absolute path.  Instead, `.dir-locals.el` stores the symbol, not the value.  This is what causes the problem with the subdirectories that become silos themselves.

As far as I can tell, we cannot do the equivalent of the backtick and comma operator in `.dir-locals.el`. This is what I always thought was happening until those bugs started surfacing.

* * *

Taking a step back, I want to avoid specifying an absolute path in the `.dir-locals.el` because I might move my `~/Documents/books` to `~/Files/books` and now my silo is broken.  Whereas with my original assumption, the `default-directory` would return the path where `.dir-locals.el` is in, so there could never be such breakage.

Does that make sense?

**Comment by MirkoHernandez** [comment]
@nobiot  the use case of the `default-directory` variable is to be able to create notes in the current buffer's directory or using dired. This is the only workflow that I use, creating the notes related to the  current buffer or directory. I don't understand why the alternative (all notes go to the same denote-directory) is the default, it seems cumbersome  having to select a directory more than just the first time each time in order to create notes in it. 

The downside is that sometimes there are problems with the links.  A simple solution is the creation  of a goto backlinks function  that sets a  denote root directory. I realize now that this wouldn't work unless the silos are inside the same root directory. 

As stated in a previous post the `dir-locals-class-alist`  variable seems to have the  information required as to what is the path of the .dir-locals.el files related to the current buffer's file. A more complex goto backlinks function could use this information to detect the proper root of a silo.

**Comment by protesilaos** [comment]
I removed the recursion and simplified how the silo root is returned.  Just posted the following on the mailing list: https://lists.sr.ht/~protesilaos/denote/%3C87fsb72nge.fsf%40protesilaos.com%3E#%3C87wn4ceu8l.fsf@protesilaos.com%3E

```
Hello folks!

I have greatly simplified the way we check for a path to the root of a
silo.  This should, in principle, remove the performance penalty that
you experienced recently.  The user option for a depth level is no more.
This works with a standard function that finds the path of the
.dir-locals.  Please test Denote with the latest commit.  I will post
this message also on the GitHub mirror.

    commit d5cf35ec2e11fb2891f15e405644768105a6a119
    Author: Protesilaos Stavrou <info@protesilaos.com>
    Date:   Mon Feb 20 08:06:15 2023 +0200

        REMOVE recursive search for silo root; keep simpler check

        This was never a good idea but I wanted to see what the implications
        are.  We do not need this anymore due to commit 3d2e1d5 which
        simplifies 'denote--silo-p'.

        Thanks to relict007, Hilde Rhyne, Mirko Hernández, Noboru
        Ota (nobiot), Alan Schmitt, and hapst3r for their participation in the
        relevant discussions:

        - https://lists.sr.ht/~protesilaos/denote/%3C87fsb72nge.fsf%40protesilaos.com%3E
        - https://lists.sr.ht/~protesilaos/denote/%3C80CBB671-D812-4EA8-8C80-85F9F4144051%40disroot.org%3E
        - https://lists.sr.ht/~protesilaos/denote/%3C87pma6t59i.fsf%40kotlak.com%3E
        - https://github.com/protesilaos/denote/issues/129 (GitHub mirror)

     README.org | 26 --------------------------
     denote.el  | 41 +----------------------------------------
     2 files changed, 1 insertion(+), 66 deletions(-)

All the best,
Prot
```

**Comment by protesilaos** [comment]
I think this is fixed now.  Thank you for your time!  Closing.
