### ISSUE TITLE
Heading WRT org-store-link references file only in denote org buffers

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/denote#198]
Hi Prot,

I just noticed that if I try to org-store-link, it always references the file instead of whatever heading/subheading I am in. This is a fairly powerful and useful facility of org-mode that I was hoping denote would retain.

I haven't looked into this that deeply; I wonder if the <<target>> notion that org-mode uses for lookups is something denote uses, and this is what interferes with the feature.

Thanks.

**Comment by protesilaos** [comment]
> From: rj ***@***.***>
> Date: Fri,  1 Dec 2023 22:17:58 -0800
>
> Hi Prot,

Hello there!

> I just noticed that if I try to org-store-link, it always references
> the file instead of whatever heading/subheading I am in. This is a
> fairly powerful and useful facility of org-mode that I was hoping
> denote would retain.

In principle, we can support this because the 'denote:' Org link type is
the same as the 'file:' type. Though I am reluctant to expand the
feature set in that direction because the features of 'file:' have not
been very reliable for me in practice.

To be concrete, I am referring to what is covered in the Org manual.
Evaluate:

    (info "(org) Search Options")

Maybe there is a way to have heading-specific and unbreakable links. If
so, I am happy to learn about it.

All the best,
Prot

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
In the upcoming version of Denote it will be possible to link to headings as well. Video demo: <https://protesilaos.com/codelog/2024-01-20-emacs-denote-link-org-headings/>
