### ISSUE TITLE
How can I figure out which version of denote is currently used?

### ISSUE THREAD

**Issue by LukasCBossert** [protesilaos/denote#301]
Hi prot,

you’re active development and support (of denote and all the other packages) are superb. With the latest functionality (e.g. having multiple "nodes" in a file with `CUSTOM_ID`) I am now considering seriously to switch from `org-roam`.

I was wondering how I can find out which version I have installed (using `DOOM emacs`). Am I missing `denote-version` (as in `org-version` or `emacs-version`)? Or is there another interactive way?

Thanks!

**Comment by protesilaos** [comment]
> From: "Lukas C. Bossert" ***@***.***>
> Date: Tue, 26 Mar 2024 00:51:47 -0700
>
> Hi prot,

Hello there!

> you’re active development and support (of denote and all the other
> packages) are superb.

Thanks!

> With the latest functionality (e.g. having multiple "nodes" in a file
> with `CUSTOM_ID`) I am now considering seriously to switch from
> `org-roam`.

If org-roam works for you, there is no strong reason to switch just to
get more of the same.

Check if you need a file-naming scheme for your long-term storage files,
regardless of their file type. This is where Denote is really different.

> I was wondering how I can find out which version I have installed
> (using `DOOM emacs`). Am I missing `denote-version` (as in
> `org-version` or `emacs-version`)? Or is there another interactive
> way?

Doom always installs directly from source, right? In that case, you are
running the latest development version. (I guees you can pin a package
to a commit, but I have not checked in a while.)

I think this is not a good default for most users because tracking a
development branch entails some instability. We change things and
experiment with stuff. While we try not to break anything, this might
happen as part of the development cycle.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by LukasCBossert** [comment]
I was rather thinking of a function that provides the info of the current version. Nothing that should break anything (I assume calling `org-version` or `emacs-version` also does not break anything).

**Comment by protesilaos** [comment]
> From: "Lukas C. Bossert" ***@***.***>
> Date: Tue, 26 Mar 2024 05:35:04 -0700
>
> I was rather thinking of a function that provides the info of the
> current version. Nothing that should break anything (I assume calling
> `org-version` or `emacs-version` also does not break anything).

I was doing that for a while with the modus-themes, but I removed it: it
was not helpful information, as it was either repeating what we already
get with 'describe-package' or it was something generic like "version
3.0.0-dev".

For the stable package, the canonical way to get its version, assuming
you are installing from the package archives (i.e. not from Git), is the
command 'describe-package'. It produces a Help buffer which shows the
version somewhere towards the top.

As for the scenario of building from source (as Doom does), then knowing
the stable version is not helpful because you are not on that version.
Nor is something like "version 3.0.0-dev". What you need in this case is
the actual commit hash, as each change constitutes its own "version"
with the state it leaves the project in.

I think Doom uses the 'straight' package manager under the hood. Last I
checked, 'straight' has a way to get the current commit of the package,
but I forgot the details...

Stable versions are recorded in the Git history with tags, so 'straight'
should be able to retrieve that data as well.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by LukasCBossert** [comment]
Thank you very much for the explanation. The clarifies it a lot. I was consulting `describe-package` but `denote` (or any other package loaded the "Doom-way") is not listed. I consider this rather  Doom-issue and not related to `denote`.
