### ISSUE TITLE
question: why IDENTIFIER and not ID

### ISSUE THREAD

**Issue by dmgerman** [protesilaos/denote#373]
Dear Prot,

First, thank you for creating this package.

I was reading the documentation and noticed that denote uses IDENTIFIER and not ID as a unique identifier for notes.

1.  Do you mind explaining the rational behind this decision? 

2. Is this optional? Is it possible to use ID instead?

thank you,

**Comment by protesilaos** [comment]
> From: dmgerman ***@***.***>
> Date: Thu,  6 Jun 2024 12:20:48 -0700
>
> Dear Prot,

Hello there!

> First, thank you for creating this package.

You are welcome!

> I was reading the documentation and noticed that denote uses
> IDENTIFIER and not ID as a unique identifier for notes.
>
> 1.  Do you mind explaining the rational behind this decision? 
>
> 2. Is this optional? Is it possible to use ID instead?

I guess by "ID" you mean the Org ID? If so, we do not use those because
(i) they are limited to Org and (ii) they are not a representation of
date+time by default.

The Denote identifiers show the date and the time. They work with any
file format. And they have no dependency on another package (there are
people who do not want to use Org).

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by dmgerman** [comment]
Thank your prompt response. I didn't know denote does require documents to be org files. 

Yes, I meant org's ID. Many of my documents already have IDs and I was wondering if I could configure denote to use them instead of IDENTIFIER. 

Based on your answer, I'll assume the answer is now. Thank you again.
