### ISSUE TITLE
Use format specifiers for the link description

### ISSUE THREAD

**Issue by protesilaos** [protesilaos/denote#469]
I think we need to review how we generate link descriptions. The idea is to have an option with format specifiers for the various file name components (like what we do with `denote-rename-buffer-format`). This way, users can set their own style with ease. Plus, it makes it easier to write custom wrappers which `let` bind the format.

The code is in the branch `link-description-format` until I merge it into `main` (subject to feedback): <https://github.com/protesilaos/denote/tree/link-description-format>.

@jeanphilippegg Since we had worked on this before, do you think my suggested change is a step in the right direction? If not, do you prefer the status quo or something else?

**Comment by jeanphilippegg** [comment]
That's good!

But are you aware that you now changed the default link description to
title-only? This is fine with me, just making sure.

In particular, links produced by `denote-link-with-signature` will also be
title-only, by default. This means that the only specific behavior of this
command is to restrict the completion candidates to files that have a
signature, which is still something. Users can always let-bind link
description options to configure the actual links.

One possibility is to reintroduce
`denote-link-description-with-signature-and-title` as the default and also
keep the new mechanism. But I am fine with the new default!

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sat, 26 Oct 2024 06:05:59 -0700
>
> That's good!

Thank you!

> But are you aware that you now changed the default link description to
> title-only? This is fine with me, just making sure.

Yes, I know. This is not finalised. I just wanted to have a prototype to
get the discussion going.

> In particular, links produced by `denote-link-with-signature` will also be
> title-only, by default. This means that the only specific behavior of this
> command is to restrict the completion candidates to files that have a
> signature, which is still something. Users can always let-bind link
> description options to configure the actual links.

I have to think about this. One possibility is to keep its current
behaviour while 'let' binding the new option. But that is probably not a
good precedent.

> One possibility is to reintroduce
> `denote-link-description-with-signature-and-title` as the default and also
> keep the new mechanism. But I am fine with the new default!

Yes, this is also fine. Maybe we can add the new user option with a nil
value. A function like 'denote-get-link-description' will use a non-nil
value, but will otherwise delegate to 'denote-link-description-with-signature-and-title'.

Though the 'denote-link-with-signature' needs to be considered either way.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
> I have to think about this. One possibility is to keep its current behaviour while 'let' binding the new option. But that is probably not a good precedent.

Yes, I don't think that is a good idea to let-bind it ourselves. Even users who use `denote-link-with-signature` may prefer a title-only description (or something else). That's why I think that the new default still works here. If you decide to go with title-only as the new default, I would be fine with it.

> Yes, this is also fine. Maybe we can add the new user option with a nil value. A function like 'denote-get-link-description' will use a non-nil value, but will otherwise delegate to 'denote-link-description-with-signature-and-title'. Though the 'denote-link-with-signature' needs to be considered either way.

If you mean that `denote-get-link-description` set to `nil` will mean to delegate to `denote-link-description-with-signature-and-title`, I would say it is preferable to cut the intermediary and set the default directly to `denote-link-description-with-signature-and-title` instead. Users who want otherwise will have to make adjustments to their config anyway. It seems less confusing this way.

Other than that, the code looks good!

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sun, 27 Oct 2024 07:16:04 -0700
>
>> I have to think about this. One possibility is to keep its current
>> behaviour while 'let' binding the new option. But that is probably
>> not a good precedent.
>
> Yes, I don't think that is a good idea to let-bind it ourselves. Even
> users who use `denote-link-with-signature` may prefer a title-only
> description (or something else). That's why I think that the new
> default still works here. If you decide to go with title-only as the
> new default, I would be fine with it.

I will check this now and see how best to deal with it. Maybe it is
easier to merge it as-is for us to experiment with the code and then we
can make changes on top. This is all in-development, after all.

>> Yes, this is also fine. Maybe we can add the new user option with a
>> nil value. A function like 'denote-get-link-description' will use a
>> non-nil value, but will otherwise delegate to
>> 'denote-link-description-with-signature-and-title'. Though the
>> 'denote-link-with-signature' needs to be considered either way.
>
> If you mean that `denote-get-link-description` set to `nil` will mean
> to delegate to `denote-link-description-with-signature-and-title`, I
> would say it is preferable to cut the intermediary and set the default
> directly to `denote-link-description-with-signature-and-title`
> instead. Users who want otherwise will have to make adjustments to
> their config anyway. It seems less confusing this way.
>
> Other than that, the code looks good!

It is needlessly complex with two user options. I think we should try to
reduce this to a single user option and handle everything internally. So
the user can specify format specifiers or a custom function. But let me
check the code and push some changes for us to work on the implementation
details.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I just merged the code into `main` after making several more changes. I did this to make it easier for us to work on the technicalities. Feel welcome to implement further changes. There is a FIXME for the `denote-link-with-signature`.

**Comment by jeanphilippegg** [comment]
> It is needlessly complex with two user options. I think we should try to reduce this to a single user option and handle everything internally. So the user can specify format specifiers or a custom function. But let me check the code and push some changes for us to work on the implementation details.

Ah! If you meant a single user option that would work with strings and
functions, then I misunderstood what you said! This is a good idea!

I see two things that seem like a downgrade for users compared to what they
had before:

- Now, when the region is active, we use it outright, with no possibility to
  handle it in some way. Previously, it was possible to have this format:
  "[region] (link)". Now, it is not possible anymore. Even setting a custom
  function would not work.

- All links now default to the title. This is a change from what we had before
  for all functions (not just `denote-link-with-signature`). Previously, links
  to file with a signature included the signature. I see no issues with
  changing the default, but it is a change.

### Proposed solution

To address the previous points, I would remove the `ignore-region` parameter.
The logic of using the region instead of the string format would be moved in
the string format section of `denote-get-link-description`.

I noticed that we used the "ignore-region" when generating a list of links.
While it may look bad, by default, if you select a region, then generate links,
I don't see it as a bug.

Here is a possibility: The user highlights "Animal: ", then open Dired, select
a few notes about animals and get this:

```
- Animal: Cat
- Animal: Dog
- Animal: Eagle
```

This is possible when the user has setup their
`denote-link-description-format` to handle regions in a special way. I would
not restrict the possibilities here. I also don't think users will be confused
if they have an active region by mistake and generate links. It is clear what
is going on. They will undo and create their links as they want them.

I also set `denote-link-description-format` to
`denote-link-description-with-signature-and-title` so that the previous
behavior is retained everywhere (and it also fixes the issue with
`denote-link-with-signature`).

I will make a pull request.

--------

As for `denote-link-with-signature`, I think there would be nothing to be
fixed even if we kept the title-only default. It does not seem bad to me.
Isn't the point of it more about the restriction of the candidates than the
format of the links?

Also, in my opinion, a command like `denote-link-with-signature` could have
been given as an example in the manual instead of included in the code,
because it is simple and handles a specific use-case.

--------

I just realized that there may still be some misunderstanding. While the new
string-format approach is good as it allows users to configure their link
descriptions in a simple way, it will always remain less flexible than the
function approach, even if we buff the string approach with features. So, the
function approach is not just kept for historical compatibility. They are not
equivalent.

For example, all the following descriptions are impossible with the string
format way:

- "[title] (generated on 2024-09-01)"
- "[signature]:  [title]" (with signature and ": " removed if signature absent)
- "[title]: [region]"
- "[title] ([some-random-number])"
- "[title]" or "[file-path]"

They all seem reasonable link descriptions, though impossible with a string
format. The function approach remains the way to go for advanced needs.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sun,  3 Nov 2024 09:12:27 -0800

> [... 4 lines elided]

> I see two things that seem like a downgrade for users compared to what they
> had before:

Thank you for taking the time to share this. The code is a work-in-progress.

> - Now, when the region is active, we use it outright, with no possibility to
>   handle it in some way. Previously, it was possible to have this format:
>   &quot;[region] (link)&quot;. Now, it is not possible anymore. Even setting a custom
>   function would not work.

Indeed, this is not good.

> - All links now default to the title. This is a change from what we had before
>   for all functions (not just `denote-link-with-signature`). Previously, links
>   to file with a signature included the signature. I see no issues with
>   changing the default, but it is a change.

I have the FIXME in the code to retain the behaviour of 'denote-link-with-signature'.
I think it makes sense for this command to deviate from the new default.
Alternatively, the new default can include the specifier for the
signature, though we have to double-check how it was before.

> ### Proposed solution
>
> To address the previous points, I would remove the `ignore-region` parameter.
> The logic of using the region instead of the string format would be moved in
> the string format section of `denote-get-link-description`.

Sounds good!

> I noticed that we used the &quot;ignore-region&quot; when generating a list of links.
> While it may look bad, by default, if you select a region, then generate links,
> I don&#39;t see it as a bug.
>
> Here is a possibility: The user highlights &quot;Animal: &quot;, then open Dired, select
> a few notes about animals and get this:
>
> ```
> - Animal: Cat
> - Animal: Dog
> - Animal: Eagle
> ```
>
> This is possible when the user has setup their
> `denote-link-description-format` to handle regions in a special way. I would
> not restrict the possibilities here. I also don&#39;t think users will be confused
> if they have an active region by mistake and generate links. It is clear what
> is going on. They will undo and create their links as they want them.

Fine, let's allow it. I just could not think of a good use-case.

> I also set `denote-link-description-format` to
> `denote-link-description-with-signature-and-title` so that the previous
> behavior is retained everywhere (and it also fixes the issue with
> `denote-link-with-signature`).
>
> I will make a pull request.

Thank you!

> --------
>
> As for `denote-link-with-signature`, I think there would be nothing to be
> fixed even if we kept the title-only default. It does not seem bad to me.
> Isn&#39;t the point of it more about the restriction of the candidates than the
> format of the links?

I think it should be about both.

> Also, in my opinion, a command like `denote-link-with-signature` could have
> been given as an example in the manual instead of included in the code,
> because it is simple and handles a specific use-case.

I agree. We should not have this to begin with, though now there are
people who are using it and it does not cost as much to maintain it in
denote.el. Maybe we can keep it as it was before, hardcoding the new
user option accordingly. Then, if users need something else, we will
document it in the manual as needed.

What do you think?

> --------
>
> I just realized that there may still be some misunderstanding. While the new
> string-format approach is good as it allows users to configure their link
> descriptions in a simple way, it will always remain less flexible than the
> function approach, even if we buff the string approach with features. So, the
> function approach is not just kept for historical compatibility. They are not
> equivalent.

Correct: the function is an option for those who need complete freedom.
In the manual I mention it is for backward-compatibility, but did not
mean to imply they are equivalent. We can clarify that point.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I merged your PR. Let me know if you think there is something else.

**Comment by jeanphilippegg** [comment]
> I merged your PR. Let me know if you think there is something else.

Since I reverted the default to what we had before, I think there is nothing left to do. The FIXME on `denote-link-with-signature` are also removed.

> Maybe we can keep it as it was before, hardcoding the new user option accordingly. Then, if users need something else, we will document it in the manual as needed. What do you think?

I agree. It could have been another good option! I am fine with both solutions!
