### ISSUE TITLE
Symbol’s function definition is void: `org-link-set-parameters`

### ISSUE THREAD

**Issue by meain** [protesilaos/denote#47]
I personally don't use `org-mode` and so does not load it by default. But with `org-mode` not loaded, loading `denote` I run into this.

```
byte-code: Symbol’s function definition is void: org-link-set-parameters
```

Commenting this out seems to fix it: https://github.com/protesilaos/denote/blob/08fa8b223926b6aee1549b87602d6bf3ac284d8b/denote-link.el#L493-L497

**Comment by protesilaos** [comment]
Hello @meain and thanks for reporthing this!

You are right!  A few weeks ago there used to be an option to opt-out of this feature.  I write "opt-out" because the default Denote file type is `.org` (per `denote-file-type`).  Perhaps we should re-introduce this option.  Or maybe there is some better way to handle this.

**Comment by meain** [comment]
Sounds great. Thank you!

**Comment by protesilaos** [comment]
Good day!  I just pushed the change.  Please give it a try.

**Comment by meain** [comment]
That seems to have fixed it!  Thank you. :D

**Comment by protesilaos** [comment]
You're welcome!
