### ISSUE TITLE
`denote-add-front-matter` fails due to incorrect type

### ISSUE THREAD

**Issue by swflint** [protesilaos/denote#492]
`denote-signature-prompt` expects a string, not a list like is returned by `denote-retrieve-filename-keywords-as-list`.  Would `denote-retrieve-filename-signature` be better here?

https://github.com/protesilaos/denote/blob/3a0bc9255bba92fc0ffa29054745852f71a29cec/denote.el#L3892

**Comment by swflint** [comment]
Sorry for creating so many issues without submitting PRs.  If my employer would provide the necessary documentation, I would have signed FSF assignment already.

**Comment by jeanphilippegg** [comment]
You're right! I will include this in my open PR later today!

**Comment by jeanphilippegg** [comment]
@protesilaos Actually, it may be easier for you to fix it directly than merging a PR. I will let you fix it!

**Comment by protesilaos** [comment]
Just pushed the change, thank you!

> @swflint Sorry for creating so many issues without submitting PRs.

This is fine. Create as many as you wish. The goal is to have a better package. Thank you for everything!

> If my employer would provide the necessary documentation, I would have signed FSF assignment already.

I am not happy with this impediment. I am requiring it because Emacs does (all my packages are "part of Emacs" in a legal sense). In principle, I am happy to reconsider. If we have lots of people who would like to contribute but cannot do it because of this requirement, then we will have to check if Denote should move to MELPA instead.

@jeanphilippegg I noticed your PR, but I did not have time to check it out. I will do it tomorrow morning. Thank you!

**Comment by swflint** [comment]
> Just pushed the change, thank you!
> 
> > @swflint Sorry for creating so many issues without submitting PRs.
> 
> This is fine. Create as many as you wish. The goal is to have a better package. Thank you for everything!

> > If my employer would provide the necessary documentation, I would have signed FSF assignment already.
> 
> I am not happy with this impediment. I am requiring it because Emacs does (all my packages are "part of Emacs" in a legal sense). In principle, I am happy to reconsider. If we have lots of people who would like to contribute but cannot do it because of this requirement, then we will have to check if Denote should move to MELPA instead.

I'm not happy with it either, but universities like money, and getting them to waive rights is a pain, especially when the technology transfer office focuses on money!  That said, there is a good chance that in a few months, I will have a more amenable employer.

Please keep Denote as a part of Emacs!  That and its relative simplicity (thus speed) are the reasons I switched to it from Org Roam!

**Comment by jeanphilippegg** [comment]
> @jeanphilippegg I noticed your PR, but I did not have time to check it out. I will do it tomorrow morning. Thank you!

No worries. You're welcome!
