### ISSUE TITLE
Consider making `denote-add-front-matter` obsolete

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#498]
It is good that this function is revisited.

Providing such a command made sense because a user could mess up their
front matter and our internal handling of front matter components was
limited. Regenerating a new clean front matter with
`denote-add-front-matter` was the way to go.

Now that all front matter components are handled by
`denote-rewrite-front-matter`, I am questioning the relevance of
`denote-add-front-matter`. `denote-rename-file` now cleans a broken
front matter.

Maybe we should make `denote-add-front-matter` obsolete now that the
limitations of `denote-rename-file` have been addressed.

The only thing new that `denote-add-front-matter` brings is to allow
adding a front matter that is out of sync with the file name, but why
would someone want to do that? And do we want to provide this feature?

What do you think?

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sat, 14 Dec 2024 20:17:16 -0800
>
> It is good that this function is revisited.

I tweaked it based on that issue and I got a sense it was superfluous,
but was not sure.

> Providing such a command made sense because a user could mess up their
> front matter and our internal handling of front matter components was
> limited. Regenerating a new clean front matter with
> `denote-add-front-matter` was the way to go.
>
> Now that all front matter components are handled by
> `denote-rewrite-front-matter`, I am questioning the relevance of
> `denote-add-front-matter`. `denote-rename-file` now cleans a broken
> front matter.
>
> Maybe we should make `denote-add-front-matter` obsolete now that the
> limitations of `denote-rename-file` have been addressed.
>
> The only thing new that `denote-add-front-matter` brings is to allow
> adding a front matter that is out of sync with the file name, but why
> would someone want to do that? And do we want to provide this feature?
>
> What do you think?

I think a 'denote-add-front-matter' only makes sense as a command
without any prompts. Otherwise, it is can lead to the mismatch you
describe.

For the "no prompts" approach to work though, it needs to convert the
title in a way that matches the user's expectations. I think we cannot
come up with a heuristic that will always work in that regard.
Capitalising the first letter or doing title-case is an okay
approximation, but still not perfect. If we do have this though, or
perhaps a variable with a title conversion function, then it is fine to
have the command. Is this worth the effort?

Otherwise, yes I agree we should deprecated the command.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
This makes sense! At some point, I think there was a desluggification
somewhere and it was removed because we probably did not consider it
worth keeping.

If we decide to provide a command with no prompts, we should probably
include the (configurable and imprecise) desluggification in
`denote-retrieve-title-or-filename` so that all renaming commands can
benefit from it. Then, a command `denote-rename-file-no-prompt` would
make sense as a convenience like other commands.

But I am not sure this is worth it, as no users has asked for it.
Users can use `denote-rename-file-title` to fix their front matter and
they can modify the title in the prompt.

In any case, this is a new feature and the current
`denote-add-front-matter` command seems effectively unnecessary
because of `denote-rename-file`, if out-of-sync file names and front
matter are undesirable.

**Comment by protesilaos** [comment]
Thank you! I just made `denote-add-front-matter` obsolete. I think we do not need to confuse users with too many similar commands.
