### ISSUE TITLE
Org mode front matter is overwritten by Denote

### ISSUE THREAD

**Issue by pprevos** [protesilaos/denote#60]
Several of my notes have an enhanced front matter, Org mode allows a lot more entry types than described in Denote, for example `#+startup:` and `#+properties:`, `#+options:`. It also allows using bespoke keywords.

When using the `denote-dired-rename-file` function, these additional lines vanish.

Can this function be rewritten to replace the content, instead of replacing the complete front matter?

**Comment by protesilaos** [comment]
Hello @pprevos!

> Several of my notes have an enhanced front matter, Org mode allows a lot more entry types than described in Denote, for example `#+startup:` and `#+properties:`, `#+options:`. It also allows using bespoke keywords.

I see.  You mention "several" which makes me think that you insert those on a case-by-case basis?  If you were doing it for all notes, the easiest way to get the renaming and creation of new notes to insert those is to modify the variable `denote-org-front-matter`.

> Can this function be rewritten to replace the content, instead of replacing the complete front matter?

If the above is not appropriate for you, then yes we will need to rewrite the code.

[ This is, by the way, why the rewriting of the front matter always asks for confirmation and never saves the underlying buffer. ]

**Comment by pprevos** [comment]
Each note has a different purpose and can have buffer local variables. I use notes a lot to develop snippets of code in Org source blocks, so I have settings for this. Other notes are math-heavy, so the Latex preview feature is on etc.

Ideally,Denote should respect the existing (non-Denote generated) lines in the front matter. 

I assume the same would apply to Markdown. Should someone want o convert the note to a website with the Hugo software for example.

**Comment by protesilaos** [comment]
Thanks for the explanation!  In this case we need a more sophisticated method to rewriting the front matter.  Now we take an all-or-nothing approach of changing the entire block.  The replacement should be done on a per-line basis.

Will think about it some more and work on it tomorrow morning (local time is close to 23h and I've been awake since ~4).

I shall keep you posted on my progress.

**Comment by protesilaos** [comment]
> Will think about it some more and work on it tomorrow morning (local time is close to 23h and I've been awake since ~4).

"Tomorrow morning" arrived earlier than expected...  I just pushed commit `4ebd1e9` in the new `refactor-front-matter-rewrite` branch.  I have tested it and it seems to work reliably, but I have not merged it into `main` yet just to be sure everything is in order.

Can you use git to test this right away?  Otherwise I will put together the relevant code you need to evaluate in order to test this.

**Comment by pprevos** [comment]
Happy to test now. It is a wonderful chill Sunday morning for me here in Australia.

Look after your health Prot, we all need sleep!

**Comment by protesilaos** [comment]
Hello again Peter,

I tested it again and updated the documentation.  The code is now in the `main` branch.

> Look after your health Prot, we all need sleep!

Thank you!  You are absolutely right.   Normally I sleep properly.  Yesterday was an exception.

**Comment by pprevos** [comment]
Hi Prot, 

I tried to test the change, but could not figure out how to jump branches.

Just renamed some test files with non-Denote Org mode keywords at the end, start and in the middle of the front matter. I also added a property drawer.

The new method respects existing Org mode keywords. Thanks for the changes.

**Comment by protesilaos** [comment]
> I tried to test the change, but could not figure out how to jump branches.

No worries!  I should have explained it.

> Just renamed some test files with non-Denote Org mode keywords at the end, start and in the middle of the front matter. I also added a property drawer.
> 
> The new method respects existing Org mode keywords. Thanks for the changes.

So you tried the `main` branch, right?  I am happy to read this.

If the rewriting works properly in all scenaria, I think it makes sense to align it with the semantics of the user option `denote-dired-rename-expert`, so that it does not ask for confirmation.  But let's leave that for the future.  Just to be sure it does the right thing.

**Comment by pprevos** [comment]
I like the confirmation. renaming is a serious task in a system with strict naming conventions.

P.S. I just also tested the Markdown dialects and text file versions - all OK.

**Comment by protesilaos** [comment]
> I like the confirmation. renaming is a serious task in a system with strict naming conventions.

Agreed!  Let's keep it as-is.

> P.S. I just also tested the Markdown dialects and text file versions - all OK.

Great!

**Comment by Nebucatnetzer** [comment]
I think I'm still seeing this in 1.2  or I'm understanding this issue wrong.
I archive all the articles that I read as Markdown files. On mobile I sometimes can't properly create them so I save a temporary copy which I then rename with Emacs.
However those files already contain a front matter.
When I rename the files with Emacs it just adds another front matter instead of merging the two.

What the files already contain:

```yaml
---
topics:
[
"https://www.republik.ch/2023/09/05/warum-wir-unseren-umgang-mit-der-welt-radikal-ueberdenken-muessen",
]
date: 2023-09-05T08:20:14+02:00
url: https://www.republik.ch/2023/09/05/warum-wir-unseren-umgang-mit-der-welt-radikal-ueberdenken-muessen
---
```

What I end up with:

```yaml
---
title: "Warum wir unseren Umgang mit der Welt radikal überdenken müssen"
date: 2023-09-05T08:20:17+02:00
tags: ["article"]
identifier: "20230905T082017"
---

---

topics:
[
"https://www.republik.ch/2023/09/05/warum-wir-unseren-umgang-mit-der-welt-radikal-ueberdenken-muessen",
]
date: 2023-09-05T08:20:14+02:00
url: https://www.republik.ch/2023/09/05/warum-wir-unseren-umgang-mit-der-welt-radikal-ueberdenken-muessen

---
```

**Comment by protesilaos** [comment]
> From: Andreas Zweili ***@***.***>
> Date: Wed,  6 Sep 2023 09:20:37 -0700

> [... 19 lines elided]

> What I end up with:
>
> ```yaml
> ---
> title: "Warum wir unseren Umgang mit der Welt radikal überdenken müssen"
> date: 2023-09-05T08:20:17+02:00
> tags: ["article"]
> identifier: "20230905T082017"
> ---
>
> ---
>
> topics:
> [
> "https://www.republik.ch/2023/09/05/warum-wir-unseren-umgang-mit-der-welt-radikal-ueberdenken-muessen",
> ]
> date: 2023-09-05T08:20:14+02:00
> url: https://www.republik.ch/2023/09/05/warum-wir-unseren-umgang-mit-der-welt-radikal-ueberdenken-muessen
>
> ---
> ```

This is indeed the expected behaviour right now.  Basically, we do not
check for the presence of front matter other than the one we know about.
The reason is that such an exercise is prone to errors.  Perhaps there
is a way to improve this and I am happy to discuss it further.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Nebucatnetzer** [comment]
I use this quite often so it would be great to have it in a future version.
Ideally Denote doesn’t overwrite data that is already present and just appends to it or takes what’s already there.

**Comment by protesilaos** [comment]
> From: Andreas Zweili ***@***.***>
> Date: Mon, 18 Sep 2023 01:09:23 -0700
>
> I use this quite often so it would be great to have it in a future version.
> Ideally Denote doesn’t overwrite data that is already present and just appends to it or takes what’s already there.

Yes, this would be nice.  We need to develop the necessary functionality
to process existing metadata and decide how to handle it from there.  It
is not an easy endeavour, but it is worth trying.

-- 
Protesilaos Stavrou
https://protesilaos.com
