### ISSUE TITLE
denote--only-note-p and related functions

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#90]
I am opening this issue to discuss the state of `denote--only-note-p`. There is this comment in the code:

```elisp
;; TODO 2022-08-11: In light of `denote--writable-and-supported-p', we
;; should either harden `denote--only-note-p' to also check for a
;; `denote-directory' or decide how to merge the two functions.  I think
;; hardening this one is more appropriate.
```

What do you mean? Should we check if the file is inside the `denote-directory`?

Also, there is this comment in `denote--retrieve-title-value`:

```elisp
;; NOTE 2022-08-11: The `or' is superfluous, but I am keeping it as a
;; reminder.  See TODO comment above `denote--only-note-p'
```

I think that when we are calling `denote--retrieve-title-value` we should be able to assume that the file is valid for this call. The check should be done elsewhere.

**Comment by protesilaos** [comment]
> What do you mean? Should we check if the file is inside the `denote-directory`?

Yes, that's the idea.  Because now it is supposed to return a "true note" but it does not check if the file is part of the `denote-directory`.  This is done in other places, but I think it makes sense to have it here.  Then we can have two types of checks:

1. Check if FILE is a "true note".
2. Check if FILE has a Denote-style file name.

Does this make sense?

I am thinking about potential extensions to Denote.  They would likely benefit from such functions (which we would eventually make public).

> Also, there is this comment in `denote--retrieve-title-value`: [...]  The check should be done elsewhere.

Agreed!  I just put it there to make the least amount of change and to add a reminder about the `denote--only-note-p` TODO.

**Comment by jeanphilippegg** [comment]
Ok, I see. Thank you!

>     1. Check if FILE is a "true note".
> 
>     2. Check if FILE has a Denote-style file name.
> 
> 
> Does this make sense?

Yes. I think it does.

**Comment by jeanphilippegg** [comment]
Closing this.

**Comment by protesilaos** [comment]
Thanks!
