### ISSUE TITLE
Denote insert immediately

### ISSUE THREAD

**Issue by sienic** [protesilaos/denote#96]
This is inspired by https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/#fast-note-insertion-for-a-smoother-writing-flow

Imagine you are writing a note, and there are some terms which are candidate for new notes (and/or linking).
So far, we need to create the node if it does not exist, and then call `denote-link`.

This is time consuming, so here's a snippet to be able to create the link without loosing focus.
If this is a thing you'd like to integrate as another function into denote, I'd be super happy to prepare a PR for it.

(I don't like the fact that I am relying in the global variable `denote-last-path`, but `org-capture` returns either `t` or `nil`, so this was the most straight-forward way of getting the `target` for `denote-link` -- any ideas on how to make this more solid?).

```elisp
(defun denote-insert-immediate ()
  (interactive)
  (let (
        (org-capture-templates '(("d" "New note (with Denote)" plain
                 (file denote-last-path)
                 #'denote-org-capture
                 :no-save t
                 :immediate-finish t
                 :kill-buffer t
                 :jump-to-captured nil))))
    (org-capture nil "d")
    (denote-link denote-last-path)))
```

**Comment by protesilaos** [comment]
Hello @sienic!

I was about to go to bed, so please wait until tomorrow for the technicalities.  I am too tired now.  The `denote-last-path` basically exists for `org-capture` due to the way that works.  Using it the way you do should be okay, though I have not tested it and I may have missed something right now.

I like the general idea here.  Though I think it would be better to implement it with the `org-capture` part.  Or is there some strong reason for that?

By decoupling it from `org-capture`, we provide the feature to all users.  Some don't use Org (I know this may sound weird, but it is true).

Anyhow, more to follow tomorrow.

**Comment by protesilaos** [comment]
Okay, I double-checked with fresh eyes.  What I wrote last night is okay.  Namely, I would prefer to decouple this from `org-capture`.

**Comment by sienic** [comment]
Hey @protesilaos, thanks for your answer!

That's a great idea, here's the snippet I came upon: 

```elisp
(defun denote-insert-immediate ()
  (interactive)
  (let ((path nil))
    (save-window-excursion
      (call-interactively #'denote)
      (save-buffer)
      (setq path (buffer-file-name (current-buffer))))
    (denote-link path)))
```
Note: Somehow `denote-last-path` does not have the desired value when I run `denote-link`, so I used instead the `buffer-file-name` workaround.


What would you think of allowing the `denote` function to use `completing-read` for its first step (i.e. setting the title), so we can select or create a node (similar to `org-roam-node-find`)?

**Comment by protesilaos** [comment]
Minor tweak:

```elisp
(defun denote-insert-immediate ()
  (interactive)
  (let (path)
    (save-window-excursion
      (call-interactively #'denote)
      (save-buffer)
      (setq path (buffer-file-name (current-buffer))))
    (denote-link path)))
```

The `denote-last-path` is only for `org-capture`.  What you did looks fine.

> What would you think of allowing the `denote` function to use `completing-read` for its first step (i.e. setting the title), so we can select or create a node (similar to `org-roam-node-find`)?

I don't quite understand what you are describing here.  Maybe I did, but I prefer to be certain.  Note that I have never used `org-roam` and am not familiar with how it works.

You mean that `denote-insert-immediate` should invoke the title prompt and then call `denote` with the relevant arguments instead of `call-interactively`?

**Comment by sienic** [comment]
Hey there,

Basically, this is the general idea (entry point is `denote-link-or-create`).
You can insert an existing node, or use the non-matching bit from the minibuffer to create the title.

```elisp
(defun denote-link-or-create (target &optional id-only)
  (interactive (list (denote--retrieve-read-file-prompt) current-prefix-arg))
  (denote-link
   (if (not (file-regular-p target))
    (let ((denote-prompts '(keywords)))
      (denote-create-in-bg (file-name-nondirectory target)))
    target))
  (insert " "))

(defun denote-create-in-bg (title)
  (interactive)
  (let ((path))
    (save-window-excursion
      (denote title)
      (save-buffer)
      (setq path (buffer-file-name (current-buffer))))
    path))
```

**Comment by protesilaos** [comment]
Sorry, I missed the notification for this one and only noticed your comment now.

> You can insert an existing node, or use the non-matching bit from the minibuffer to create the title.

Looks promising!  How should we proceed?

- Do we flesh it out fully to work with the interactive version of `denote` (meaning that it parses the `denote-prompts`)?

- Do we handle the `denote-templates`?

- Should this be in denote.el or do you think it should be documented in the manual as a Do-It-Yourself kind of idea?

**Comment by uningan** [comment]
> From: Protesilaos Stavrou ***@***.***>
> Date: Mon, 05 Sep 2022 05:26:05 -0700
>
> Sorry, I missed the notification for this one and only noticed your comment now.
>
>> You can insert an existing node, or use the non-matching bit from the minibuffer to create the title.
>
> Looks promising!  How should we proceed?
>
> - Do we flesh it out fully to work with the interactive version of `denote` (meaning that it parses the `denote-prompts`)?
>
> - Do we handle the `denote-templates`?
>
> - Should this be in denote.el or do you think it should be documented in the manual as a Do-It-Yourself kind of idea?

My 2 cents:

I think this flow is important enough to be part of core denote. Is a
big boost in interconected ideas/notes.

-- 
Juanjo Presa
https://nadanix.com

**Comment by protesilaos** [comment]
> My 2 cents:
> 
> I think this flow is important enough to be part of core denote. Is a
> big boost in interconected ideas/notes.

@uningan Yes, I am okay with this.

**Comment by sienic** [comment]
> Do we flesh it out fully to work with the interactive version of denote (meaning that it parses the denote-prompts)?

That's a good idea.  What do you think of splitting the logic that creates a node, from that which visits the node (from the point of view of the user)?

> Do we handle the denote-templates?

I am not that acquainted with this part of the logic, but if we can find a proper abstraction I guess it should be possible to plug templates to that part of the logic.  Perhaps, `link-or-create` can autocomplete notes, whereas `link-or-create-template` could just prompt the template afterwards, or accept the template as a prefix (e.g. `book::Elements(Euclid)`.

> Should this be in denote.el or do you think it should be documented in the manual as a Do-It-Yourself kind of idea?

I agree with @uningan.  On top of that, several solutions (org-roam, roam-research, logseq) use the approach of "link_or_create' nodes for faster note taking.

**Comment by protesilaos** [comment]
> I agree with @uningan. On top of that, several solutions (org-roam, roam-research, logseq) use the approach of "link_or_create' nodes for faster note taking.

Very well!  This will be added to denote.el.  We all agree.

> That's a good idea. What do you think of splitting the logic that creates a node, from that which visits the node (from the point of view of the user)?

It is tricky because `denote` only has the full functionality when called interactively.  Otherwise we need to replicate some of its conditionality.

The most basic I can get, while retaining full compatibility with what we have, is this:

```elisp
(defun denote-link-after-create (&optional id-only)
  "Create new note in the background and link to it directly.
With optional ID-ONLY as a prefix argument create a link that
consists of just the identifier.  Else try to also include the
file's title.  This has the same meaning as in `denote-link'."
  (interactive "P")
  (let (path)
    (save-window-excursion
      (call-interactively #'denote)
      (save-buffer)
      (setq path (buffer-file-name)))
    (denote-link path id-only)))
```

Note though that it does not have the "OR" functionality that you are looking for.  Perhaps we can have this as well?  I still need to check how best to handle the "OR" case.

**Comment by protesilaos** [comment]
A quick follow-up to what I wrote earlier: https://github.com/protesilaos/denote/issues/96#issuecomment-1240118199

The following code gets the job done but the `denote-link-or-create` does not retain the user's input at the prompt to link to a file.  If it does not find a file, it simply starts the process of creating a new one using the familiar `denote` interactivity.

I did it this way because (i) it is simple, (ii) works with what we have, (iii) lets the user search for links with regular expressions or out-of-order queries (per `orderless`) without creating a note with some awkward title.  About the last point, I often perform a search like `_emacs theme palette ef` where everything is out-of-order.

```elisp
;;;###autoload
(defun denote-link-after-create (&optional id-only)
  "Create new note in the background and link to it directly.

Use `denote' interactively to produce the new note.  Its doc
string explains which prompts will be used and under what
conditions.

With optional ID-ONLY as a prefix argument create a link that
consists of just the identifier.  Else try to also include the
file's title.  This has the same meaning as in `denote-link'."
  (interactive "P")
  (let (path)
    (save-window-excursion
      (call-interactively #'denote)
      (save-buffer)
      (setq path (buffer-file-name)))
    (denote-link path id-only)))

;;;###autoload
(defun denote-link-or-create (target &optional id-only)
  "Use `denote-link' on TARGET file.
If TARGET does not exist, invoke `denote-link-after-create' which
 calls `denote' interactively."
  (interactive (list (denote--retrieve-read-file-prompt) current-prefix-arg))
  (if (file-exists-p target)
      (denote-link target id-only)
    (call-interactively #'denote-link-after-create)))
```

What do you think?

**Comment by sienic** [comment]
@protesilaos great, thanks!  That's very neat and well simple enough 🚀 

How about naming the first function as `denote-create-note-and-link` 🤔 

I wonder if `create` can be used across the source code to denote (no pun intended) notes which get saved, and `build` for notes that haven't been saved.  Taking one step back, what's the reason not to stored notes when calling `denote` alone?

**Comment by sienic** [comment]
> Very well! I will implement them tomorrow morning as they also need to be documented and I am about to go to bed.

🙇 thanks!

> I used the denote-link prefix to make it consistent with the other denote-link- forms

Makes sense.  I guess my point of confusion was the `after-create` part which to me reads like a hook (although in elisp hooks have explicit suffices).  Now I read it as an action which happens after creating. 👍 

> By "store" you mean "save"? 

Yes. 

> It is a safety precaution.

I see.  Then we will drop this safety precaution with the current issue. I was wondering if we could align this, thus my question. 🙂

**Comment by protesilaos** [comment]
> 🙇 thanks!

You are welcome!

> > I used the denote-link prefix to make it consistent with the other denote-link- forms

> Makes sense.  I guess my point of confusion was the `after-create` part which to me reads like a hook (although in elisp hooks have explicit suffices).  Now I read it as an action which happens after creating. 👍

I like "the after creating" more.  This looks better: `denote-link-after-creating`.

> I see.  Then we will drop this safety precaution with the current issue. I was wondering if we could align this, thus my question. 🙂

I did it that way because `denote-link` needs to ensure that the target is actually a file.  Whereas `buffer-file-name` can also work with a buffer.  Basically, here we need to be sure that we are creating an actual link.

However, it may be wrong to think this way and we need to then review the conditionality of `denote--retrieve-filename-identifier`.  Instead of `file-exists-p` it could use `denote--file-has-identifier-p`.

Thoughts?

I will double-check tomorrow morning.

**Comment by protesilaos** [comment]
Good day!  I published the new code.  Here it is:

```elisp
;;;###autoload
(defun denote-link-after-creating (&optional id-only)
  "Create new note in the background and link to it directly.

Use `denote' interactively to produce the new note.  Its doc
string explains which prompts will be used and under what
conditions.

With optional ID-ONLY as a prefix argument create a link that
consists of just the identifier.  Else try to also include the
file's title.  This has the same meaning as in `denote-link'.

IMPORTANT NOTE: Normally, `denote' does not save the buffer it
produces for the new note.  This is a safety precaution to not
write to disk unless the user wants it (e.g. the user may choose
to kill the buffer, thus cancelling the creation of the note).
However, for this command the creation of the note happens in the
background and the user may miss the step of saving their buffer.
We thus have to save the buffer in order to (i) establish valid
links, and (ii) retrieve whatever front matter from the target
file."
  (interactive "P")
  (let (path)
    (save-window-excursion
      (call-interactively #'denote)
      (save-buffer)
      (setq path (buffer-file-name)))
    (denote-link path id-only)))

;;;###autoload
(defun denote-link-or-create (target &optional id-only)
  "Use `denote-link' on TARGET file, creating it if necessary.

If TARGET file does not exist, call `denote-link-after-creating'
which runs the `denote' command interactively to create the file.
The established link will then be targeting that new file.

With optional ID-ONLY as a prefix argument create a link that
consists of just the identifier.  Else try to also include the
file's title.  This has the same meaning as in `denote-link'."
  (interactive (list (denote--retrieve-read-file-prompt) current-prefix-arg))
  (if (file-exists-p target)
      (denote-link target id-only)
    (call-interactively #'denote-link-after-creating)))

(defalias 'denote-link-to-existing-or-new-note (symbol-function 'denote-link-or-create))
```

The relevant entry in the manual: <https://protesilaos.com/emacs/denote#h:9e41e7df-2aac-4835-94c5-659b6111e6de>.

Please let me know if there is something else, otherwise we can close this issue.  Thanks again for the feedback thus far!

[ We can always refine this further.  It is part of development, after all. ]

**Comment by sienic** [comment]
Awesome, thanks again!

**Comment by protesilaos** [comment]
You are welcome!
